### ISSUE TITLE
Use IPC helper & ServiceFramework on our services

### ISSUE THREAD

**Issue by wwylele** [citra-emu/citra#2531]
Since #2027 is merged, we should get started to apply it to our services. This issue is to record the assignment of each service and the process of them. 

Update: we also need to convert them into new `ServiceFramework` and ditch some old interface of IPCHelpers. Please do not use those `[[deprecated]]` functions (including `Push/PopHandle`) in the new `ServiceFramework`.

We have the following services, neglecting services without any actual implemented/stubbed functions: (bold ones are service that are already implemented a lot and should be taken more care)
- [x] ac (#2992)
- [x] **am**
- [x] **apt** (#2533) (need new service framework) (#3421)
- [x] boss
- [x] **cam** (#2722) (need new service framework) (#3239)
- [x] cecd
- [x] **cfg**
- [x] csnd
- [x] **dsp**
- [x] **err:f** (#3190)
- [x] **frd** (#3469)
- [x] **gsp** (#3307)
- [x] **fs** (#3441)
- [x] **hid** (#3304)
- [x] **ir** (#3248)
- [x] **ldr:ro** (#2532) (need new service framework) (#3192)
- [x] mic (#3253)
- [x] **ndm**
- [x] nfc (#3476)
- [x] nim
- [x] ns
- [x] **nwm** (partially done)
- [x] **ptm** (#2710) (need new service framework)(#3361)
- [x] **soc**
- [x] **srv** (#2774)
- [x] ssl
- [x] **y2r** (#3367)

Please comment below if you are going to take over one from this list.

~~Also note that @Lectem will have follow up PRs to IPC helper itself. Currently these functions are planed to add:~~ Already done

**Comment by JohnnyPony** [comment]
I am currently working on the ac service.

**Comment by wwylele** [comment]
Unresolved problems presented in #2532 : 
Most real system model checks param translation descriptor, and returns `ERROR_INVALID_DESCRIPTOR` on failure. Currently the check is handled by IPCHelper with `DEBUG_ASSERT_MSG`. We need to consider the importance of this (usually game won't hit this error) and think of a proper way to handle it.

**Comment by tgsm** [comment]
#2532 is merged, so I am assuming ldr:ro can be checked off now.

**Comment by wwylele** [comment]
Probably we can wait for #2646, and do IPC helper and log rewrite for each module at the same time

**Comment by yuriks** [comment]
I don't think that's a good idea. If you can do and submit 2 things separately then you should. Makes it easier to review, avoid conflicts, etc.

**Comment by wwylele** [comment]
Update: as the new service framework fully implemented, all services need to transform to it.

**Comment by lioncash** [comment]
I'll claim the mic service to help out with this
